Video/AplicacaoCurso/Eventos.IO/src/Eventos.IO.Site/Controllers/EventosController.cs
using System;
using Eventos.IO.Application.Interfaces;
using Eventos.IO.Application.ViewModels;
using Eventos.IO.Domain.Core.Notifications;
using Eventos.IO.Domain.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Eventos.IO.Site.Controllers
{
    [Route("")]
    public class EventosController : BaseController
    {
        private readonly IEventoAppService _eventoAppService;

        public EventosController(IEventoAppService eventoAppService, 
                                 IDomainNotificationHandler<DomainNotification> notifications,
                                 IUser user) : base(notifications, user)
        {
            _eventoAppService = eventoAppService;
        }

        [Route("")]
        [Route("proximos-eventos")]
        public IActionResult Index()
        {
            return View(_eventoAppService.ObterTodos());
        }

        [Route("meus-eventos")]
        [Authorize(Policy = "PodeLerEventos")]        
        public IActionResult MeusEventos()
        {
            return View(_eventoAppService.ObterEventoPorOrganizador(OrganizadorId));
        }

        [Route("dados-do-evento/{id:guid}")]
        public IActionResult Details(Guid? id)
        {
            if (id == null) { return NotFound(); }

            var eventoViewModel = _eventoAppService.ObterPorId(id.Value);

            if (eventoViewModel == null) { return NotFound(); }

            return View(eventoViewModel);
        }

        [Route("novo-evento")]
        [Authorize(Policy = "PodeGravar")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("novo-evento")]
        [Authorize(Policy = "PodeGravar")]
        public IActionResult Create(EventoViewModel eventoViewModel)
        {
            if (!ModelState.IsValid) return View(eventoViewModel);

            eventoViewModel.OrganizadorId = OrganizadorId;

            _eventoAppService.Registrar(eventoViewModel);

            ViewBag.RetornoPost = OperacaoValida() ? 
                "success,Evento registrado com sucesso!" : 
                "error,Evento não registrado! Verifique as mensagens.";

            return View(eventoViewModel);
        }

        [Route("editar-evento/{id:guid}")]
        [Authorize(Policy = "PodeGravar")]
        public IActionResult Edit(Guid? id)
        {
            if (id == null) { return NotFound(); }

            var eventoViewModel = _eventoAppService.ObterPorId(id.Value);
            if (eventoViewModel == null) { return NotFound(); }

            if (!ValidarAutoridadeEvento(eventoViewModel.OrganizadorId))
            {
                return RedirectToAction("MeusEventos", _eventoAppService.ObterEventoPorOrganizador(OrganizadorId));
            }

            return View(eventoViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("editar-evento")]
        [Authorize(Policy = "PodeGravar")]
        public IActionResult Edit(EventoViewModel eventoViewModel)
        {
            if (!ValidarAutoridadeEvento(eventoViewModel.OrganizadorId))
            {
                return RedirectToAction("MeusEventos", _eventoAppService.ObterEventoPorOrganizador(OrganizadorId));
            }

            if (!ModelState.IsValid) return View(eventoViewModel);

            eventoViewModel.OrganizadorId = OrganizadorId;
            _eventoAppService.Atualizar(eventoViewModel);

            ViewBag.RetornoPost = OperacaoValida() ?
                "success,Evento registrado com sucesso!" :
                "error,Evento não pode ser atualizado! Verifique as mensagens.";

            if (_eventoAppService.ObterPorId(eventoViewModel.Id).Online)
            {
                eventoViewModel.Endereco = null;
            }
            else
            {
                eventoViewModel = _eventoAppService.ObterPorId(eventoViewModel.Id);
            }
                     

            return View(eventoViewModel);
        }

        [Route("excluir-evento/{id:guid}")]
        [Authorize(Policy = "PodeGravar")]
        public IActionResult Delete(Guid? id)
        {
            if (id == null) { return NotFound(); }

            var eventoViewModel = _eventoAppService.ObterPorId(id.Value);

            if (!ValidarAutoridadeEvento(eventoViewModel.OrganizadorId))
            {
                return RedirectToAction("MeusEventos", _eventoAppService.ObterEventoPorOrganizador(OrganizadorId));
            }

            if (eventoViewModel == null) { return NotFound(); }

            return View(eventoViewModel);
        }

        [Authorize(Policy = "PodeGravar")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Route("excluir-evento/{id:guid}")]
        public IActionResult DeleteConfirmed(Guid id)
        {
            var eventoViewModel = _eventoAppService.ObterPorId(id);
            if (!ValidarAutoridadeEvento(eventoViewModel.OrganizadorId))
            {
                return RedirectToAction("MeusEventos", _eventoAppService.ObterEventoPorOrganizador(OrganizadorId));
            }

            _eventoAppService.Excluir(id);
            return RedirectToAction("Index");
        }

        [Authorize(Policy = "PodeGravar")]
        [Route("incluir-endereco/{id:guid}")]
        public IActionResult IncluirEndereco(Guid? id)
        {
            if (id == null)
                return NotFound();

            var eventoViewModel = _eventoAppService.ObterPorId(id.Value);
            return PartialView("_IncluirEndereco", eventoViewModel);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("incluir-endereco/{id:guid}")]
        [Authorize(Policy = "PodeGravar")]
        public IActionResult IncluirEndereco(EventoViewModel eventoViewModel)
        {
            ModelState.Clear();
            eventoViewModel.Endereco.EventoId = eventoViewModel.Id;
            _eventoAppService.AdicionarEndereco(eventoViewModel.Endereco);

            if (OperacaoValida())
            {
                var url = Url.Action("ObterEndereco", "Eventos", new { id = eventoViewModel.Id });
                return Json(new { success = true, url = url });
            }

            return PartialView("_IncluirEndereco", eventoViewModel);
        }

        [Authorize(Policy = "PodeGravar")]
        [Route("atualizar-endereco/{id:guid}")]
        public IActionResult AtualizarEndereco(Guid? id)
        {
            if (id == null)
                return NotFound();

            var eventoViewModel = _eventoAppService.ObterPorId(id.Value);
            return PartialView("_AtualizarEndereco", eventoViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("atualizar-endereco/{id:guid}")]
        [Authorize(Policy = "PodeGravar")]
        public IActionResult AtualizarEndereco(EventoViewModel eventoViewModel)
        {
            ModelState.Clear();
            _eventoAppService.AtualizarEndereco(eventoViewModel.Endereco);

            if (OperacaoValida())
            {
                var url = Url.Action("ObterEndereco", "Eventos", new { id = eventoViewModel.Id });
                return Json(new { success = true, url = url });
            }

            return PartialView("_AtualizarEndereco", eventoViewModel);
        }

        [Route("listar-endereco/{id:guid}")]
        public IActionResult ObterEndereco(Guid id)
        {
            return PartialView("_DetalhesEndereco", _eventoAppService.ObterPorId(id));
        }

        private bool ValidarAutoridadeEvento(Guid organizadorId)
        {
            return (organizadorId == OrganizadorId);
        }
    }
}

Video/AplicacaoCurso/Eventos.IO/src/Eventos.IO.Site/ViewComponents/SummaryViewComponent.cs
using Eventos.IO.Domain.Core.Notifications;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Eventos.IO.Site.ViewComponents
{
    public class SummaryViewComponent : ViewComponent
    {
        private readonly IDomainNotificationHandler<DomainNotification> _notifications;

        public SummaryViewComponent(IDomainNotificationHandler<DomainNotification> notifications)
        {
            _notifications = notifications;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var notificacoes = await Task.FromResult(_notifications.GetNotifications());
            notificacoes.ForEach(c => ViewData.ModelState.AddModelError(string.Empty, c.Value));

            return View();
        }
    }
}

Video/AplicacaoCurso/Eventos.IO/src/Eventos.IO.Site/Views/Eventos/Create.cshtml
@model Eventos.IO.Application.ViewModels.EventoViewModel
@{
    ViewData["Title"] = "Registrar Novo Evento";
}

<h2>@ViewData["Title"]</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Preencha todos os dados corretamente</h4>
        <hr />

        <vc:summary />

        <div class="form-group">
            <label asp-for="Nome" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Nome" class="text-danger" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="DescricaoCurta" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="DescricaoCurta" class="form-control" />
                <span asp-validation-for="DescricaoCurta" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="DescricaoLonga" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <textarea rows="5" asp-for="DescricaoLonga" class="form-control"></textarea>
                <span asp-validation-for="DescricaoLonga" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Categoria" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                @Html.Partial("_Categorias")
                <span asp-validation-for="Categoria" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="DataInicio" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="DataInicio" class="form-control" />
                <span asp-validation-for="DataInicio" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="DataFim" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="DataFim" class="form-control" />
                <span asp-validation-for="DataFim" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset col-md-10">
                <div class="checkbox">
                    <input asp-for="Gratuito" />
                    <label asp-for="Gratuito"></label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Valor" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset col-md-10">
                <div class="checkbox">
                    <input asp-for="Online" />
                    <label asp-for="Online"></label>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="NomeEmpresa" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="NomeEmpresa" class="form-control" />
                <span asp-validation-for="NomeEmpresa" class="text-danger"></span>
            </div>
        </div>

        <div id="EnderecoForm">
            <hr />
            <div class="form-group">
                <label asp-for="Endereco.Logradouro" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Endereco.Logradouro" class="form-control" />
                    <span asp-validation-for="Endereco.Logradouro" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Endereco.Numero" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Endereco.Numero" class="form-control" />
                    <span asp-validation-for="Endereco.Numero" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Endereco.Complemento" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Endereco.Complemento" class="form-control" />
                    <span asp-validation-for="Endereco.Complemento" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Endereco.Bairro" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Endereco.Bairro" class="form-control" />
                    <span asp-validation-for="Endereco.Bairro" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Endereco.Cep" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Endereco.Cep" class="form-control" />
                    <span asp-validation-for="Endereco.Cep" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Endereco.Cidade" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Endereco.Cidade" class="form-control" />
                    <span asp-validation-for="Endereco.Cidade" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Endereco.Estado" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    @Html.Partial("_Estados")
                    <span asp-validation-for="Endereco.Estado" class="text-danger"></span>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="btSubmit" value="Registrar" class="btn btn-success" />
                <a asp-action="Index" class="btn btn-info">Voltar para a lista</a>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/locales/bootstrap-datepicker.pt-BR.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/locales/bootstrap-datepicker.pt.min.js"></script>

    <script>
        ValidacoesEvento();
        ajaxModal();
    </script>

    @{
        if (ViewBag.RetornoPost != null)
        {
            var notificacao = ViewBag.RetornoPost.ToString().Split(',');

            <script>
                toastr["@notificacao[0]"]("@notificacao[1]");
            </script>

            if (@notificacao[0] == "success")
            {
                <script>
                    toastr.options.onHidden = function () {
                        window.location = "http://localhost:6246/eventos/meuseventos";
                    };

                    toastr.options.onclick = function () {
                        window.location = "http://localhost:6246/eventos/meuseventos";
                    };

                    toastr.options.onCloseClick = function () {
                        window.location = "http://localhost:6246/eventos/meuseventos";
                    };

                    $('#btSubmit').prop("disabled", true);
                </script>
            }
        }
    }
}

Video/AplicacaoCurso/Eventos.IO/src/Eventos.IO.Site/Views/Eventos/Details.cshtml
@using Eventos.IO.Application.ViewModels;

@model EventoViewModel

@{
    ViewData["Title"] = @Model.Nome;
}

<div class="jumbotron">
    <h2>@ViewData["Title"]</h2>
    <h4>@Model.DescricaoCurta</h4>
</div>
<div class="container">
    <div>
        <div class="row">
            @Html.DisplayFor(modelItem => Model.DescricaoLonga)
        </div>
        <hr />
        <br />
        <div class="row">
            <b>Quando:</b><br />
            @Model.DataInicio.ToString("d") até @Model.DataFim.ToString("d")
        </div>
        <br />
        <div class="row">
            <b>Valor:</b><br />
            @{
                if (Model.Gratuito){
                @Html.DisplayName("Gratuito");
                }
                else
                {
                @Html.DisplayFor(modelItem => Model.Valor);
                }
            }
        </div>
        <br />
        <div class="row">
            <b>Tipo de Evento:</b><br />
            @{
                var categoria = new CategoriaViewModel().ListarCategorias().FirstOrDefault(c => c.Id == Model.CategoriaId);
            }
        </div>
        <br />
        <div class="row">
            <b>Organizado Por:</b><br />
            @Html.DisplayFor(modelItem => modelItem.NomeEmpresa)
        </div>
        <br />
        <div class="row">
            <b>Onde?</b><br />
            @{
                if (Model.Online){
                    @Html.DisplayName("Evento Online")
                }
                else
                {
                    <iframe width="600" height="450" frameborder="0" style="border:0" src="file.html" allowfullscreen></iframe>    
                }
            }
        </div>
    </div>
    <div>
        <a href="javascript:history.go(-1)" class="btn btn-info">Voltar</a>
    </div>
</div>
<script>
    ajaxModal();
</script>

Video/AplicacaoCurso/Eventos.IO/src/Eventos.IO.Site/Views/Eventos/Edit.cshtml
@model Eventos.IO.Application.ViewModels.EventoViewModel
@{
    ViewData["Title"] = "Editar Evento";
}

<h2>@ViewData["Title"]</h2>

<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker3.min.css" rel="stylesheet" />

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Lembre-se que muitas pessoas já podem ter visto este evento antes de mudar datas e etc</h4>
        <hr />

        <vc:summary />

        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="OrganizadorId" />

        <div class="form-group">
            <label asp-for="Nome" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Nome" class="text-danger" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="DescricaoCurta" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="DescricaoCurta" class="form-control" />
                <span asp-validation-for="DescricaoCurta" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="DescricaoLonga" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <textarea rows="5" asp-for="DescricaoLonga" class="form-control"></textarea>
                <span asp-validation-for="DescricaoLonga" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Categoria" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                @Html.Partial("_Categorias")
                <span asp-validation-for="Categoria" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="DataInicio" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="DataInicio" type="text" asp-format="{0:dd/MM/yyyy}" class="form-control" />
                <span asp-validation-for="DataInicio" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="DataFim" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="DataFim" type="text" asp-format="{0:dd/MM/yyyy}" class="form-control" />
                <span asp-validation-for="DataFim" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset col-md-10">
                <div class="checkbox">
                    <input asp-for="Gratuito" />
                    <label asp-for="Gratuito"></label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Valor" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input data-val-number="O valor está em formato inválido." asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset col-md-10">
                <div class="checkbox">
                    <input asp-for="Online" />
                    <label asp-for="Online"></label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="NomeEmpresa" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="NomeEmpresa" class="form-control" />
                <span asp-validation-for="NomeEmpresa" class="text-danger"></span>
            </div>
        </div>        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="btSubmit" value="Atualizar Evento" class="btn btn-success" />
                <a asp-action="Index" class="btn btn-info">Voltar para a Lista</a>
            </div>
        </div>
    </div>
</form>

<div id="EnderecoForm">
    <div id="enderecoTarget">
        @Html.Partial("_DetalhesEndereco")
    </div>
</div>

<div id="myModal" class="modal fade in">
    <div class="modal-dialog">
        <div class="modal-content">
            <div id="myModalContent"></div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/locales/bootstrap-datepicker.pt-BR.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/locales/bootstrap-datepicker.pt.min.js"></script>

    <script>
        ValidacoesEvento();
        ajaxModal();
    </script>

    @{
        if (ViewBag.RetornoPost != null)
        {
            var notificacao = ViewBag.RetornoPost.ToString().Split(',');

            <script>              
                toastr["@notificacao[0]"]("@notificacao[1]");
            </script>

            if (@notificacao[0] == "success")
            {
                <script>
                    toastr.options.onHidden = function () {
                        window.location = "http://localhost:6246/eventos/meuseventos";
                    };

                    toastr.options.onclick = function () {
                        window.location = "http://localhost:6246/eventos/meuseventos";
                    };

                    toastr.options.onCloseClick = function () {
                        window.location = "http://localhost:6246/eventos/meuseventos";
                    };

                    $('#btSubmit').prop("disabled", true);
                </script>
            }
        }
    }
}

Video/AplicacaoCurso/Eventos.IO/src/Eventos.IO.Site/Views/Eventos/Index.cshtml
@model IEnumerable<Eventos.IO.Application.ViewModels.EventoViewModel>
@{
    ViewData["Title"] = "Lista de Próximos Eventos";
}

<h2>@ViewData["Title"]</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataInicio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataFim)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Valor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Online)
            </th>
            <th></th>
        </tr>        
    </thead>
    <tbody>
        @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @item.DataInicio.ToString("d")
                </td>
                <td>
                    @item.DataFim.ToString("d")
                </td>
                <td>
                    @{
                        if (item.Gratuito)
                        {
                            @Html.DisplayName("Gratuito")
                        }
                        else
                        {
                            @Html.DisplayFor(modelItem => item.Valor)
                        }
                    }
                </td>            
                <td>
                    @Html.DisplayFor(modelItem => item.Online)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary">
                        <span class="glyphicon glyphicon-search"></span> Ver Detalhes
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

Video/AplicacaoCurso/Eventos.IO/src/Eventos.IO.Site/Views/Eventos/MeusEventos.cshtml
@model IEnumerable<Eventos.IO.Application.ViewModels.EventoViewModel>
@{
    ViewData["Title"] = "Meus Eventos";
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="col-md-12">
        <div class="pull-left">
            <a asp-action="Create" class="btn btn-primary">
                <span title="Novo Evento" class="glyphicon glyphicon-plus-sign"></span>
            </a>
        </div>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataInicio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataFim)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Valor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Online)
            </th>
            <th></th>
        </tr>        
    </thead>
    <tbody>
        @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @item.DataInicio.ToString("d")
                </td>
                <td>
                    @item.DataFim.ToString("d")
                </td>
                <td>
                    @{
                        if (item.Gratuito)
                        {
                            @Html.DisplayName("Gratuito")
                        }
                        else
                        {
                            @Html.DisplayFor(modelItem => item.Valor)
                        }
                    }
                </td>            
                <td>
                    @Html.DisplayFor(modelItem => item.Online)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning">
                        <span class="glyphicon glyphicon-pencil"></span> 
                    </a>
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary">
                        <span class="glyphicon glyphicon-search"></span>
                    </a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

Video/AplicacaoCurso/Eventos.IO/src/Eventos.IO.Site/Views/Eventos/_AtualizarEndereco.cshtml
@using Eventos.IO.Application.ViewModels;

@model EventoViewModel

@{ 
    ViewData["Title"] = "Atualizar Endereço";
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">
        <span aria-hidden="true">x</span><span class="sr-only">Fechar</span>
    </button>
    <h4 class="modal-title">@ViewData["Title"]</h4>
</div>

<form asp-action="AtualizarEndereco">
    <div class="modal-body">
        <div class="form-horizontal">
            <vc:summary />

            @Html.Partial("_Endereco")

            <div class="modal-footer">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Atualizar Endereço" class="btn btn-success" />
                    <input type="button" class="btn btn-info" value="Fechar" data-dismiss="modal" />
                </div>
            </div>
        </div>
    </div>
</form>

Video/AplicacaoCurso/Eventos.IO/src/Eventos.IO.Site/Views/Eventos/_Categorias.cshtml
@using Eventos.IO.Application.ViewModels;
@model Eventos.IO.Application.ViewModels.EventoViewModel
@{
    var categoriaViewModel = new CategoriaViewModel();
    var categorias = (IEnumerable<SelectListItem>)categoriaViewModel.ListarCategorias();
}
<select asp-for="CategoriaId" asp-items="@categorias" class="form-control"></select> 

Video/AplicacaoCurso/Eventos.IO/src/Eventos.IO.Site/Views/Eventos/_IncluirEndereco.cshtml
@using Eventos.IO.Application.ViewModels;

@model EventoViewModel
@{ 
    ViewData["Title"] = "Incluir Endereço";
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">
        <span aria-hidden="true">x</span><span class="sr-only">Fechar</span>
    </button>
    <h4 class="modal-title">@ViewData["Title"]</h4>
</div>

<form asp-action="IncluirEndereco">
    <div class="modal-body">
        <div class="form-horizontal">
            <vc:summary />
            @{ 
                Html.Partial("_Endereco");
            }

            <div class="modal-footer">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Adicionar Endereço" class="btn btn-success" />
                    <input type="button" class="btn btn-info" value="Fechar" data-dismiss="modal" />
                </div>
            </div>
        </div>
    </div>
</form>